# Generated by Django 2.1.7 on 2019-04-01 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('mentor_name', models.CharField(max_length=45)),
                ('mentor_contact', models.CharField(max_length=40)),
                ('mentor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('station_address', models.CharField(max_length=200)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS2.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=45)),
                ('student_contact', models.CharField(max_length=40)),
                ('student_email', models.EmailField(max_length=254)),
                ('check', models.CharField(max_length=2000)),
                ('organization_mentor', models.CharField(max_length=50)),
                ('organization_email_id', models.EmailField(max_length=254)),
                ('organization_contact', models.CharField(max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS2.Station')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(default=0)),
                ('tasksplanned', models.CharField(default='', max_length=2500)),
                ('taskscompleted', models.CharField(default='', max_length=2500)),
                ('variation', models.CharField(default='', max_length=2500)),
                ('nextweek', models.CharField(default='', max_length=2500)),
                ('learning', models.CharField(default='', max_length=2500)),
                ('equipments', models.CharField(default='', max_length=2500)),
                ('comment', models.CharField(default='', max_length=2500)),
                ('lock', models.IntegerField(default=0)),
                ('submissionDate', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS2.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('week_no', 'user_id')},
        ),
    ]
